spring.application.name=games-api

spring.datasource.url=jdbc:h2:mem:games-api
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50
